# GET Request with Body
GET http://localhost:8080/webservice/restful/server.php/core_course_get_courses
AUTHORIZATION: e786e74631683916cc4cc277707ad5c3
CONTENT_TYPE: application/json
ACCEPT: application/json
{"options": {"ids": ["1"]}}




# GET with URL Encoded params
GET http://localhost:8080/webservice/restful/server.php/core_course_get_courses?options[ids][]=1
AUTHORIZATION: e786e74631683916cc4cc277707ad5c3
ACCEPT: application/json
CONTENT_TYPE: application/urlencoded

