; -*- mode: restclient;-*-


# GET Request with Body
GET http://localhost:8080/webservice/restful/server.php/core_course_get_courses
AUTHORIZATION: 8410c8268bfa0a3dc1e0ed8fb15aed86
CONTENT_TYPE: application/json
ACCEPT: application/json
{"options": {"ids": ["1"]}}




# GET with URL Encoded params
GET http://localhost:8080/webservice/restful/server.php/core_course_get_courses?options[ids][]=1
AUTHORIZATION: 8410c8268bfa0a3dc1e0ed8fb15aed86
ACCEPT: application/json
CONTENT_TYPE: application/urlencoded



# Site Info
GET http://localhost:8080/webservice/restful/server.php/core_webservice_get_site_info?serviceshortnames[]=x
AUTHORIZATION: 8410c8268bfa0a3dc1e0ed8fb15aed86
ACCEPT: application/json
CONTENT_TYPE: application/urlencoded
